// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmezwgcmsrrlcydhoriv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtZXp3Z2Ntc3JybGN5ZGhvcml2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2OTM5ODEsImV4cCI6MjA2MDI2OTk4MX0.Iot-mjgUpx8WIdWRdpHBZbTl3oUK3OqARo7kciJwZHE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);